### ISSUE TITLE
release 0.06 on windows 7

### ISSUE THREAD

**Issue by jchenpku** [RitterHou/stinger#3]
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.main()
        /Users/hourui/go/src/github.com/ritterhou/stinger/local/main.go:32 +0x7e
d

**Comment by RitterHou** [comment]
这个大概是因为在新的release上面使用了旧的配置文件吧，这边没做默认值处理，接下来会加上

**Comment by jchenpku** [comment]
是的，更新了配置文件就没问题了。
